<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.0.1 (Python 3.11.0 on win32)" generated="20230317 11:06:45.058" rpa="false" schemaversion="3">
<suite id="s1" name="BestTest" source="C:\Users\เบส\Desktop\TISCO\Mobile App\BestTest">
<suite id="s1-s1" name="TestCase" source="C:\Users\เบส\Desktop\TISCO\Mobile App\BestTest\TestCase">
<suite id="s1-s1-s1" name="MyFund" source="C:\Users\เบส\Desktop\TISCO\Mobile App\BestTest\TestCase\MyFund">
<suite id="s1-s1-s1-s1" name="Top New Feed" source="C:\Users\เบส\Desktop\TISCO\Mobile App\BestTest\TestCase\MyFund\Top_New_Feed">
<suite id="s1-s1-s1-s1-s1" name="MyFund" source="C:\Users\เบส\Desktop\TISCO\Mobile App\BestTest\TestCase\MyFund\Top_New_Feed\MyFund.robot">
<test id="s1-s1-s1-s1-s1-t1" name="TESTCASE004_Single Feed Specific Target By Schedule" line="49">
<kw name="Open Application" library="AppiumLibrary">
<arg>${URL}</arg>
<arg>platformName=${PLATFORM}</arg>
<arg>platformVersion=${DEVICE_TARGET}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>app=${APP_LOCATION}</arg>
<arg>automationName=appium</arg>
<arg>noReset=true</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<msg timestamp="20230317 11:06:47.276" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000028DB0407A50&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20230317 11:06:49.298" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000028DAFF51750&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20230317 11:06:51.322" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000028DAFE5EB10&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20230317 11:06:53.364" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20230317 11:06:53.364" endtime="20230317 11:06:53.369"/>
</kw>
<msg timestamp="20230317 11:06:53.371" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20230317 11:06:53.373" level="FAIL">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000028DAC8ED490&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</msg>
<status status="FAIL" starttime="20230317 11:06:45.244" endtime="20230317 11:06:53.375"/>
</kw>
<kw name="Press Button Accept Cookie" library="Single_Feed_Broadcast_All_Keywords">
<status status="NOT RUN" starttime="20230317 11:06:53.375" endtime="20230317 11:06:53.376"/>
</kw>
<kw name="Press Icon Notification" library="Single_Feed_Broadcast_All_Keywords">
<status status="NOT RUN" starttime="20230317 11:06:53.376" endtime="20230317 11:06:53.376"/>
</kw>
<kw name="Verify Message Inbox Record 1" library="Single_Feed_Broadcast_All_Keywords">
<arg>${varTopicCase4}</arg>
<arg>${varDetailCase4}</arg>
<status status="NOT RUN" starttime="20230317 11:06:53.376" endtime="20230317 11:06:53.377"/>
</kw>
<kw name="Select Topic" library="Single_Feed_Broadcast_All_Keywords">
<arg>${varTopicCase4}</arg>
<status status="NOT RUN" starttime="20230317 11:06:53.377" endtime="20230317 11:06:53.377"/>
</kw>
<kw name="Verify Message Detail In Inbox" library="Single_Feed_Broadcast_All_Keywords">
<arg>${varTopicCase4}</arg>
<arg>${varDetailCase4}</arg>
<status status="NOT RUN" starttime="20230317 11:06:53.377" endtime="20230317 11:06:53.377"/>
</kw>
<kw name="Verify Button Back" library="Single_Feed_Broadcast_All_Keywords">
<status status="NOT RUN" starttime="20230317 11:06:53.378" endtime="20230317 11:06:53.378"/>
</kw>
<doc>1.อันไหนที่รอ API เดี๋ยวให้ dev ทำให้ เพื่อยิงลบ data
2.ส่วน OTP พี่กะว่าจะสร้าง id card สำหรับ automate โดยเฉพาะ แล้วให้เค้า fix OTP ให้ ว่าต้องเป็นค่าอะไร</doc>
<status status="FAIL" starttime="20230317 11:06:45.242" endtime="20230317 11:06:53.378">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000028DAC8ED490&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</status>
</test>
<status status="FAIL" starttime="20230317 11:06:45.083" endtime="20230317 11:06:53.379"/>
</suite>
<status status="FAIL" starttime="20230317 11:06:45.081" endtime="20230317 11:06:53.381"/>
</suite>
<status status="FAIL" starttime="20230317 11:06:45.080" endtime="20230317 11:06:53.382"/>
</suite>
<status status="FAIL" starttime="20230317 11:06:45.078" endtime="20230317 11:06:53.383"/>
</suite>
<status status="FAIL" starttime="20230317 11:06:45.061" endtime="20230317 11:06:53.385"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="BestTest">BestTest</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1" name="TestCase">BestTest.TestCase</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1-s1" name="MyFund">BestTest.TestCase.MyFund</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1-s1-s1" name="Top New Feed">BestTest.TestCase.MyFund.Top New Feed</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1-s1-s1-s1" name="MyFund">BestTest.TestCase.MyFund.Top New Feed.MyFund</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20230317 11:06:47.276" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000028DB0407A50&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20230317 11:06:49.298" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000028DAFF51750&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20230317 11:06:51.322" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000028DAFE5EB10&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20230317 11:06:53.371" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
